In [2]:
import numpy as np
from PIL import Image

In [5]:
def preprocess_img_test(img_path, new_width, new_height):
    img = Image.open(img_path).convert('L')
    new_img = img.resize(size = (new_width, new_height), resample=Image.Resampling.LANCZOS)
    img_array =np.array(new_img)

    return new_img

In [7]:
img_test = preprocess_img_test(img_path=r'C:\Users\jwolowikow\Pictures\Saved Pictures\digit recognizer test images\test_resize_4.png',
                          new_width=28, new_height=28)
img_test

In [13]:
arr = np.ndarray(shape=(1,2,1,2), dtype=int)

arr.shape

(1, 2, 1, 2)

In [16]:
import tensorflow as tf
import matplotlib.pyplot as plt

mnist = tf.keras.datasets.mnist

(_, _), (x_test, _) = mnist.load_data()

image= x_test[0]

# Plot and save the image
plt.imshow(image, cmap='gray')
plt.axis('off')  # Turn off axis labels
plt.savefig('mnist_image.png', bbox_inches='tight', pad_inches=0)  # Save the image
plt.close()  # Close the plot


In [17]:
from keras.models import load_model

model = load_model('digit_recognizer_v4.keras')

model.summary()



Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 reshape_6 (Reshape)         (None, 28, 28, 1)         0         
                                                                 
 random_contrast_6 (RandomC  (None, 28, 28, 1)         0         
 ontrast)                                                        
                                                                 
 random_width_3 (RandomWidt  (None, 28, None, 1)       0         
 h)                                                              
                                                                 
 random_height_2 (RandomHei  (None, None, None, 1)     0         
 ght)                                                            
                                                                 
 batch_normalization_22 (Ba  (None, None, None, 1)     4         
 tchNormalization)                                  

In [22]:
model.layers[4].get_weights()

[array([0.972678], dtype=float32),
 array([0.18203789], dtype=float32),
 array([33.558434], dtype=float32),
 array([5286.572], dtype=float32)]